<?php

/**
 * Created by PhpStorm.
 * User: lin11
 * Date: 2016/10/29
 * Time: 14:14
 */
class ErrorsController extends Controller
{
    function login_fail(){
        echo "fail";
    }
    function nologin(){
        echo 'nologin';
    }
    function checkLogin()
    {
        // TODO: Change the autogenerated stub
    }
}