<?php

/**
 * Created by PhpStorm.
 * User: lin11
 * Date: 2016/10/28
 * Time: 20:30
 */
class SignController extends Controller
{
    function login(){
        $this->needRender(true);
    }
    function sign_in(){
        $sign = new UserCollection();
        $isCorrect= $sign->loginVerify($_POST['username'],$_POST['password']);
        if($isCorrect){
            @header("location:/personal/sport_data");
        }else{
            @header("location:/errors/login_fail");
        }
        //
    }
    function checkLogin()
    {
         // TODO: Change the autogenerated stub
    }
}