<?php

/**
 * Created by PhpStorm.
 * User: lin11
 * Date: 2016/10/28
 * Time: 20:30
 */
class SignController extends Controller
{
    function login(){
        $this->needRender(true);
    }
    function sign_in(){
        @header("location:/personal/sport_data");
    }
    function checkLogin()
    {
         // TODO: Change the autogenerated stub
    }
}